export const GET_USERS_LOADING = 'GET_USERS_LOADING'
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS'
export const GET_USERS_FAILED = 'GET_USERS_FAILED'

export const POST_USERS_LOADING = 'POST_USERS_LOADING'