apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-statefulset
  labels:
    app: mongo
spec:
  serviceName: mongo-service
  replicas: 2
  # serviceName: mongodb
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
        role: mongo
        replicaset: MainRepSet
    spec:
      containers:
        - name: mongodb
          image: mongo:5.0
          ports:
            - name: mongodb-port
              containerPort: 27017
              hostPort: 27017
         

          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: password
          volumeMounts:
          - mountPath: /data/db
            name: mongo-claim0  
      volumes:
      - name: mongo-claim0
        persistentVolumeClaim:
          claimName: mongo-claim0
      
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  # labels:
  #   app: mongo-service
spec:
  # type: NodePort
  ports:
    - name: mongo
      protocol: TCP
      port: 27017
      targetPort: 27017
  selector:
    app: mongo
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: mongo-claim0
  name: mongo-claim0
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi